# Generated by Django 4.1.3 on 2022-11-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('DayHappening', models.DateTimeField()),
                ('Threshold', models.CharField(choices=[('custom pick', 'Custom Pick'), ('10 minute before', '10 Minute Before'), ('3 days before', '3 Days Before'), ('10 days before', '10 Days Before')], default='10 minute before', max_length=100)),
                ('CustomPick', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
