# Generated by Django 4.1.3 on 2022-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmmodel',
            name='TimesUp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarmmodel',
            name='Threshold',
            field=models.CharField(choices=[('custom pick', 'Custom Pick'), ('10 minutes before', '10 Minutes Before'), ('3 days before', '3 Days Before'), ('10 days before', '10 Days Before')], default='10 minutes before', max_length=100),
        ),
    ]
